stages:
  - build
  - test

before_script:
  - chcp 65001

job_build:
  stage: build
  script:
    - dotnet build -c Release
  artifacts:
    untracked: true
    expire_in: 60 mins

job_test:
  stage: test
  script:
    - dotnet test --no-build -c Release -s ../settings.runsettings /p:CollectCoverage=true /p:CoverletOutputFormat=teamcity /p:Exclude=[*.Tests]* /p:Threshold=60 /p:ThresholdType=line
  coverage: "/key='CodeCoverageL' value='(.*)'/"